"""
visualize.py

Render the physics-test scenarios (tests/scenarios.py) to labeled PNG montages
so you can eyeball that each tested state looks right. For every scenario it:

  * saves the baked map to <out>/maps/<name>.npz, and
  * renders a montage to <out>/render/<name>.png with one row per view mode and
    one column per captured timestep.

It also writes <out>/fixtures.toml so you can open any scenario live in the
interactive viewer:

    python src/main.py --config fixtures/fixtures.toml \
        --maps-dir fixtures/maps --map hot_blob

Usage:
    python tools/visualize.py                 # all scenarios -> ./fixtures
    python tools/visualize.py --scenario hot_blob --out /tmp/viz
"""

import argparse
import os
import sys
from pathlib import Path

# Headless rendering: use SDL's dummy video driver so no window is required.
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))
sys.path.insert(0, str(_ROOT / "tests"))

import pygame  # noqa: E402

from firecracker_env import FirecrackerEnv  # noqa: E402
from map_loader import save_map             # noqa: E402
from scenarios import DEFAULT_GRID, VISUALS  # noqa: E402

PAD = 8
LABEL_H = 20
TITLE_H = 30
BG = (18, 18, 18)
FG = (210, 210, 210)


def _viz_config(config: dict, window: int) -> dict:
    """Copy a scenario config with the display window enlarged for legibility."""
    env_cfg = dict(config.get("environment", {}))
    env_cfg["window_size"] = window
    return {**config, "environment": env_cfg}


def render_montage(env: FirecrackerEnv, modes, frames, title: str) -> pygame.Surface:
    pygame.font.init()
    font = pygame.font.SysFont("monospace", 13)
    title_font = pygame.font.SysFont("monospace", 16, bold=True)

    # Capture each (mode, timestep) frame as the simulation advances.
    captures: dict[tuple[str, int], "pygame.surfarray.array"] = {}
    last = max(frames)
    for t in range(last + 1):
        if t in frames:
            for mode in modes:
                env._current_mode = mode
                captures[(mode.name, t)] = env.render()  # (H, W, 3)
        if t < last:
            env.step(0)

    tile = env.grid_size * env._pixel_scale
    cell_w = tile + PAD
    cell_h = tile + LABEL_H
    title_surface = title_font.render(title, True, FG)
    width = max(PAD + len(frames) * cell_w, title_surface.get_width() + 2 * PAD)
    height = TITLE_H + len(modes) * (cell_h + PAD)

    montage = pygame.Surface((width, height))
    montage.fill(BG)
    montage.blit(title_surface, (PAD, 6))

    for i, mode in enumerate(modes):
        for j, t in enumerate(frames):
            arr = captures[(mode.name, t)]
            # surfarray wants (W, H, 3); render() returns (H, W, 3).
            surface = pygame.surfarray.make_surface(arr.transpose(1, 0, 2))
            x = PAD + j * cell_w
            y = TITLE_H + i * (cell_h + PAD)
            montage.blit(surface, (x, y))
            montage.blit(
                font.render(f"{mode.name.lower()} @ t={t}", True, FG),
                (x, y + tile + 3),
            )
    return montage


def write_fixtures_toml(path: Path, window: int) -> None:
    names = ", ".join(f'"{n}"' for n in VISUALS)
    path.write_text(
        "# Auto-generated by tools/visualize.py — config for viewing the test\n"
        "# fixtures in the interactive viewer. This is a partial SI config; every\n"
        "# key it omits falls back to the code default. Fire is enabled so you can\n"
        "# click to ignite and watch behavior on these analytic SI maps.\n"
        f"# Available maps: {names}\n\n"
        "[maps]\n"
        'dir  = "maps"\n'
        'name = ""\n\n'
        "[environment]\n"
        f"grid_size   = {DEFAULT_GRID}\n"
        f"window_size = {window}\n\n"
        "[fire]\n"
        "enabled    = true\n"
        "spawn_fire = false\n\n"
        "[radiation]\n"
        "enabled = true\n\n"
        "[channeling]\n"
        "enabled = true\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Render physics-test scenarios to PNG montages")
    parser.add_argument("--out", default="fixtures", help="output directory (default: fixtures)")
    parser.add_argument("--scenario", help="render only this scenario (default: all)")
    parser.add_argument("--window", type=int, default=256, help="per-tile render size in px")
    args = parser.parse_args()

    out = Path(args.out)
    maps_dir = out / "maps"
    render_dir = out / "render"
    maps_dir.mkdir(parents=True, exist_ok=True)
    render_dir.mkdir(parents=True, exist_ok=True)

    names = [args.scenario] if args.scenario else list(VISUALS)
    for name in names:
        if name not in VISUALS:
            raise SystemExit(f"Unknown scenario '{name}'. Available: {list(VISUALS)}")
        builder, modes, frames, doc = VISUALS[name]
        config, map_data = builder()
        save_map(maps_dir / f"{name}.npz", map_data)

        env = FirecrackerEnv(
            config=_viz_config(config, args.window),
            render_mode="rgb_array",
            maps_dir=str(maps_dir),
            map_name=name,
        )
        env.reset(seed=0)
        montage = render_montage(env, modes, frames, f"{name} — {doc}")
        png = render_dir / f"{name}.png"
        pygame.image.save(montage, str(png))
        env.close()
        print(f"  {name:18s} -> {png}")

    write_fixtures_toml(out / "fixtures.toml", args.window)
    print(f"\nMaps:    {maps_dir}/")
    print(f"Montages: {render_dir}/")
    print(f"Interactive: python src/main.py --config {out}/fixtures.toml "
          f"--maps-dir {out}/maps --map <name>")


if __name__ == "__main__":
    main()
